image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

stages:
  - build
  - environment
  - staging
  - production

build:
  stage: build
  script:
    - mvn clean install

environment:
  stage: environment
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

staging:
    type: deploy
    stage: staging
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - staging

production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master

after_script:
  - echo "By the word of Seht, I am up."