# Propriedades do Spring
server.port: 8080
spring.application.name: The Grand Prognosticator
logging.file: logs/grand-prognosticator.log

# Propriedades do robô
bot:
  discord:
    volume: 10
    playing: The Elder Scrolls Online
    api:
      token: NTYwMjA0Nzk5OTI1Mjg4OTYy.Xok-nQ.dG3ipppFr1kUAig69-iuKc8IY9k
      id: 560204799925288962
      secret: k62c9pibRwP0l6e62UQj9KGudQERkaU4
    message:
      operator: "!gp"
      footer:
        icon: http://img1.wikia.nocookie.net/__cb20120612190227/elderscrolls/images/f/f7/TESOnlineIcon.png
        text: The Grand Prognosticator. By the Word of Seht, I am bound.
    guild:
      id: 597965640564998144
      channel:
        log: 655609448731246602
        general: 597965640564998146
        campaign: 597966376988049416
  rpg.sheet.dir:
    save: '@project.build.directory@/sheets/save'
    load: '@project.build.directory@/sheets/load'
  watson:
    apikey: lC4m88gsx2ID_BWKlgoUqJmxZ_mkbxWOa1YEFzQ670be
    assistantid: 694772e9-3301-42e6-8cf1-65d24a82d683
  youtube.apikey: AIzaSyA9Sz1TJoz2K0rX70EBoO99yv56EQZdams
